version = 1
name = "helix-resolve-git-ref"
description = "Get to know the Fastly Compute@Edge environment with a basic starter that demonstrates routing, simple synthetic responses and overriding caching rules."
authors = ["trieloff@adobe.com"]
language = "assemblyscript"
service_id = "4KRGKViu9n9TaxCNorUeig"
